[package]
name = "hello"
version = "0.0.0"
edition = "2018"

[dependencies]
lambda_http = { git = "https://github.com/awslabs/aws-lambda-rust-runtime", branch = "master" }
tokio = { version = "1", features = ["macros"] }
serde_json = "1.0"